### ISSUE TITLE
wildcard feature broken

### ISSUE THREAD

**Issue by acb764se** [tcsh-org/tcsh#49]
This happens on Microsoft's WSL2 version:

/tmp> /bin/tcsh --version
tcsh 6.21.00 (Astron) 2019-05-08 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,nd,color,filec
/tmp> touch file1 file2 file3
/tmp> ls file[1-2]
file1  file2
/tmp> ls file[2-3]
file1  file2  file3

This keeps happening if I mv away my .cshrc and .login, but stops if I go to /bin/bash:

/tmp>setenv
setenv: command not found
/tmp>export isThisSomeBash=yes
/tmp>echo $isThisSomeBash 
yes
/tmp>ls file[1-2]
file1  file2
/tmp>ls file[2-3]
file2  file3

**Comment by alzwded** [comment]
Isn't this the same as https://github.com/tcsh-org/tcsh/issues/13 aka https://bugs.astron.com/view.php?id=81 ?

It was fixed in 6.22.

I'm not sure how/when the distros used by WSL get updated (ask Microsoft? check the windows store?), and you haven't mentioned what distro you have installed under WSL.

I recall someone complaining about old tcsh packages in Ubuntu, @suominen set up a [deb repo](https://deb.tcsh.org). If you are using Ubuntu or Debian you can add it to your apt sources and get the latest and greatest regardless of what's currently in their respective archives.
