### ISSUE TITLE
SVN script uses python 2.5 which has reached EOL

### ISSUE THREAD

**Issue by Sigmanificient** [tcsh-org/tcsh#72]
Hi, the `svn` script uses a version of python which has reached End Of Life in 2008.

See: `#! /usr/bin/env python2.5`

Moreover, Python 2 has been depreciated since 2020.
This script needs to be update to a newer version of python.

**Comment by lukem** [comment]
While python2 is EOL, various common older platforms still don't ship python3 in a useful form. (E.g., RHEL < 7.6).

If supporting older platforms that have python2 but not python3  is still desirable for tcsh, then supporting both python2 and python3 in the one script is useful.

I've found it's not too difficult in trivial scripts to support both python2 and python3 even without compatibility shims such as "six", as long as you're not dealing with unicode strings (where more complicated workarounds are required due to python3 changes).

**Comment by suominen** [comment]
Fixed in #73.
