### ISSUE TITLE
missing tags for versions past 6.18.1

### ISSUE THREAD

**Issue by lukem** [tcsh-org/tcsh#8]
It looks like the releases past 6.18.1 are missing their tags.
Was there a missing "git push --tags" ?

PS: I suggest tagging annotated tags using "git tag -a" instead of just "git tag".

**Comment by zoulasc** [comment]
On Jul 27,  4:19pm, notifications@github.com (Luke Mewburn) wrote:
-- Subject: [tcsh] missing tags for versions past 6.18.1 (#8)

| It looks like the releases past 6.18.1 are missing their tags.
| Was there a missing "git push --tags" ?
| 
| PS: I suggest tagging annotated tags using "git tag -a" instead of just "git tag".
| 

I added git push --tags; let's see if that fixes it next time.

Thanks,

christos
